spring:
  application:
    name: item-service
eureka:
  client:    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka

---
spring:  profiles: item1-8001
server:
  port: 8001
---
spring:
  profiles: item2-8002
server:
  port: 8002      