eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka
server:
  port: 3001
spring:
  application:
    name: zuul
#以下zuul.routes是默认配置，可以不用配置
zuul:
  routes:
    item-service: /item-service/**
    order-service: /order-service/**
    user-service: /user-service/**
  retryable: true
  
  
  
